## Modelo Una sola Variable

In [2]:
from math import sqrt
from numpy import split
from numpy import array
from pandas import read_csv

In [4]:
dataset = read_csv('household_power_consumption_days.csv', header=0,
infer_datetime_format=True, parse_dates=['datetime'], index_col=['datetime'])
data=dataset.values

In [5]:
#Split dataset

train, test = data[1:-328], data[-328:-6]
# restructure into windows of weekly data
train = array(split(train, len(train)/7))
test = array(split(test, len(test)/7))


In [26]:
len(test)

46

In [12]:
#to_supervised
n_input=14
n_out=7
data = train.reshape((train.shape[0]*train.shape[1], train.shape[2]))
X, y = list(), list()
in_start = 0
# step over the entire history one time step at a time
for _ in range(len(data)):
    # define the end of the input sequence
    in_end = in_start + n_input
    out_end = in_end + n_out
    # ensure we have enough data for this instance
    if out_end < len(data):
        x_input = data[in_start:in_end, 0]
        x_input = x_input.reshape((len(x_input), 1))
        X.append(x_input)
        y.append(data[in_end:out_end, 0])
    # move along one time step
    in_start += 1
train_x, train_y = array(X), array(y)

In [13]:
train_x[0]

array([[3390.46 ],
       [2203.826],
       [1666.194],
       [2225.748],
       [1723.288],
       [2341.338],
       [4773.386],
       [2550.012],
       [2743.12 ],
       [3934.11 ],
       [1528.76 ],
       [2072.638],
       [3174.392],
       [2796.108]])

In [31]:
train_y[0]

array([3494.196, 2749.004, 1269.236, 1014.054, 3259.412, 2713.364,
       1508.378])

In [32]:
dataset.head(20)

Global_active_power  Global_reactive_power    Voltage  \
datetime                                                            
2006-12-16             1209.176                 34.922   93552.53   
2006-12-17             3390.460                226.006  345725.32   
2006-12-18             2203.826                161.792  347373.64   
2006-12-19             1666.194                150.942  348479.01   
2006-12-20             2225.748                160.998  348923.61   
2006-12-21             1723.288                144.434  347096.41   
2006-12-22             2341.338                186.906  347305.75   
2006-12-23             4773.386                221.470  345795.95   
2006-12-24             2550.012                149.900  348029.91   
2006-12-25             2743.120                240.280  350495.90   
2006-12-26             3934.110                165.102  347940.63   
2006-12-27             1528.760                178.902  351025.00   
2006-12-28             2072.638                208.876  350306.40   
2006-12-29             3174.392                196.394  346854.68   
2006-12-30             2796.108                312.142  346377.15   
2006-12-31             3494.196                150.852  345451.07   
2007-01-01             2749.004                148.166  345785.73   
2007-01-02             1269.236                190.342  348399.04   
2007-01-03             1014.054                196.728  350722.21   
2007-01-04             3259.412                202.302  345240.43   

            Global_intensity  Kitchen  Laundry_room  Electronic_devices  \
datetime                                                                  
2006-12-16            5180.8      0.0         546.0              4926.0   
2006-12-17           14398.6   2033.0        4187.0             13341.0   
2006-12-18            9247.2   1063.0        2621.0             14018.0   
2006-12-19            7094.0    839.0        7602.0              6197.0   
2006-12-20            9313.0      0.0        2648.0             14063.0   
2006-12-21            7266.4   1765.0        2692.0             10456.0   
2006-12-22            9897.0   3151.0         350.0             11131.0   
2006-12-23           20200.4   2669.0         425.0             14726.0   
2006-12-24           11002.2   1703.0        5082.0              6891.0   
2006-12-25           11450.2   6620.0        1962.0              5795.0   
2006-12-26           16341.0   1086.0        2533.0             14979.0   
2006-12-27            6505.2      0.0         314.0              6976.0   
2006-12-28            8764.2   2207.0        4419.0              9176.0   
2006-12-29           13350.8   1252.0        5162.0             11329.0   
2006-12-30           11952.6   3072.0        7893.0             12516.0   
2006-12-31           14687.4      0.0         347.0              6502.0   
2007-01-01           11400.4      0.0         352.0              5880.0   
2007-01-02            5348.2      0.0         348.0              6562.0   
2007-01-03            4340.2      0.0         344.0              4765.0   
2007-01-04           13648.6   1051.0        7597.0             10896.0   

            Residual_Energy  
datetime                     
2006-12-16     14680.933319  
2006-12-17     36946.666732  
2006-12-18     19028.433281  
2006-12-19     13131.900043  
2006-12-20     20384.800011  
2006-12-21     13808.466697  
2006-12-22     24390.300043  
2006-12-23     61736.433386  
2006-12-24     28824.199967  
2006-12-25     31341.666629  
2006-12-26     46970.500071  
2006-12-27     18189.333302  
2006-12-28     18741.966606  
2006-12-29     35163.533293  
2006-12-30     23120.800045  
2006-12-31     51387.600002  
2007-01-01     39584.733275  
2007-01-02     14243.933346  
2007-01-03     11791.900019  
2007-01-04     34779.533289

## Modelo de varias variables

In [16]:
#to_supervised
n_input=14
n_out=7
data = train.reshape((train.shape[0]*train.shape[1], train.shape[2]))
Xm, ym = list(), list()
in_start = 0
# step over the entire history one time step at a time
for _ in range(len(data)):
    # define the end of the input sequence
    in_end = in_start + n_input
    out_end = in_end + n_out
    # ensure we have enough data for this instance
    if out_end < len(data):
        # x_input = data[in_start:in_end, 0]
        # x_input = x_input.reshape((len(x_input), 1))
        Xm.append(data[in_start:in_end, :])
        ym.append(data[in_end:out_end, 0])
    # move along one time step
    in_start += 1
train_xm, train_ym = array(Xm), array(ym)

In [17]:
train_xm[0]

array([[3.39046000e+03, 2.26006000e+02, 3.45725320e+05, 1.43986000e+04,
        2.03300000e+03, 4.18700000e+03, 1.33410000e+04, 3.69466667e+04],
       [2.20382600e+03, 1.61792000e+02, 3.47373640e+05, 9.24720000e+03,
        1.06300000e+03, 2.62100000e+03, 1.40180000e+04, 1.90284333e+04],
       [1.66619400e+03, 1.50942000e+02, 3.48479010e+05, 7.09400000e+03,
        8.39000000e+02, 7.60200000e+03, 6.19700000e+03, 1.31319000e+04],
       [2.22574800e+03, 1.60998000e+02, 3.48923610e+05, 9.31300000e+03,
        0.00000000e+00, 2.64800000e+03, 1.40630000e+04, 2.03848000e+04],
       [1.72328800e+03, 1.44434000e+02, 3.47096410e+05, 7.26640000e+03,
        1.76500000e+03, 2.69200000e+03, 1.04560000e+04, 1.38084667e+04],
       [2.34133800e+03, 1.86906000e+02, 3.47305750e+05, 9.89700000e+03,
        3.15100000e+03, 3.50000000e+02, 1.11310000e+04, 2.43903000e+04],
       [4.77338600e+03, 2.21470000e+02, 3.45795950e+05, 2.02004000e+04,
        2.66900000e+03, 4.25000000e+02, 1.47260000e+04, 6.

In [22]:
dataset.head(20)

Global_active_power  Global_reactive_power    Voltage  \
datetime                                                            
2006-12-16             1209.176                 34.922   93552.53   
2006-12-17             3390.460                226.006  345725.32   
2006-12-18             2203.826                161.792  347373.64   
2006-12-19             1666.194                150.942  348479.01   
2006-12-20             2225.748                160.998  348923.61   
2006-12-21             1723.288                144.434  347096.41   
2006-12-22             2341.338                186.906  347305.75   
2006-12-23             4773.386                221.470  345795.95   
2006-12-24             2550.012                149.900  348029.91   
2006-12-25             2743.120                240.280  350495.90   
2006-12-26             3934.110                165.102  347940.63   
2006-12-27             1528.760                178.902  351025.00   
2006-12-28             2072.638                208.876  350306.40   
2006-12-29             3174.392                196.394  346854.68   
2006-12-30             2796.108                312.142  346377.15   
2006-12-31             3494.196                150.852  345451.07   
2007-01-01             2749.004                148.166  345785.73   
2007-01-02             1269.236                190.342  348399.04   
2007-01-03             1014.054                196.728  350722.21   
2007-01-04             3259.412                202.302  345240.43   

            Global_intensity  Kitchen  Laundry_room  Electronic_devices  \
datetime                                                                  
2006-12-16            5180.8      0.0         546.0              4926.0   
2006-12-17           14398.6   2033.0        4187.0             13341.0   
2006-12-18            9247.2   1063.0        2621.0             14018.0   
2006-12-19            7094.0    839.0        7602.0              6197.0   
2006-12-20            9313.0      0.0        2648.0             14063.0   
2006-12-21            7266.4   1765.0        2692.0             10456.0   
2006-12-22            9897.0   3151.0         350.0             11131.0   
2006-12-23           20200.4   2669.0         425.0             14726.0   
2006-12-24           11002.2   1703.0        5082.0              6891.0   
2006-12-25           11450.2   6620.0        1962.0              5795.0   
2006-12-26           16341.0   1086.0        2533.0             14979.0   
2006-12-27            6505.2      0.0         314.0              6976.0   
2006-12-28            8764.2   2207.0        4419.0              9176.0   
2006-12-29           13350.8   1252.0        5162.0             11329.0   
2006-12-30           11952.6   3072.0        7893.0             12516.0   
2006-12-31           14687.4      0.0         347.0              6502.0   
2007-01-01           11400.4      0.0         352.0              5880.0   
2007-01-02            5348.2      0.0         348.0              6562.0   
2007-01-03            4340.2      0.0         344.0              4765.0   
2007-01-04           13648.6   1051.0        7597.0             10896.0   

            Residual_Energy  
datetime                     
2006-12-16     14680.933319  
2006-12-17     36946.666732  
2006-12-18     19028.433281  
2006-12-19     13131.900043  
2006-12-20     20384.800011  
2006-12-21     13808.466697  
2006-12-22     24390.300043  
2006-12-23     61736.433386  
2006-12-24     28824.199967  
2006-12-25     31341.666629  
2006-12-26     46970.500071  
2006-12-27     18189.333302  
2006-12-28     18741.966606  
2006-12-29     35163.533293  
2006-12-30     23120.800045  
2006-12-31     51387.600002  
2007-01-01     39584.733275  
2007-01-02     14243.933346  
2007-01-03     11791.900019  
2007-01-04     34779.533289

In [24]:
train_x

1092

## Dataset en Minutos

In [3]:
dataset_m = read_csv('household_power_consumption.csv', header=0,
infer_datetime_format=True, parse_dates=['datetime'], index_col=['datetime'])
# data=dataset.values

In [6]:
dataset_m.shape


(2075259, 8)